// saving the data
const products = [
    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "JinKO 625W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "LPBA4A200",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/JinKo Solar Panels Range Datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "JinKO 615W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "LPBA4A200",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/JinKo Solar Panels Range Datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "JinKO 580W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "LPBA4A200",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/JinKo Solar Panels Range Datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "JinKO 555W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "LPBA4A200",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/JinKo Solar Panels Range Datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "JinKO 550W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "LPBA4A200",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/JinKo Solar Panels Range Datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "JinKO 545W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "LPBA4A200",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/JinKo Solar Panels Range Datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "JinKO 480W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "LPBA4A200",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/JinKo Solar Panels Range Datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "JinKO 475W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "LPBA4A200",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/JinKo Solar Panels Range Datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "JinKO 465W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "LPBA4A200",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/JinKo Solar Panels Range Datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "JinKO 440W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "LPBA4A200",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/JinKo Solar Panels Range Datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "felicity 540W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "FL-MSD-540W",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity Solar Panel 540W.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "felicity 450W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "FL-MSD-450W",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity Solar Panel 450W.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      name: "felicity 400W Solar Panel",
      id: "234askfhjebjdyuw1",
      brandID: "FL-MSD-400W",
      description: "High-efficiency monocrystalline solar panel with half-cut cell technology for improved performance and durability.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Mono", "Monocrystalline","Solar", "Solar Photovoltaic", "Solar PV", "PV", "Panels"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Products - HalfCut PV Panelx1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity Solar Panel 450W.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Hybrid 5KVA & 3KVA Wallmounted Inverter.jpg",
      name: "5KVA Offgrid Inverter ",
      id: "234askfhjebjdyuw1",
      brandID: "FL-MSD-400W",
      description: "High-efficiency 5KVA Off-grid wall-mounted inverter with pure sine wave output, compatible with solar and battery storage.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [
        "5KVA Inverter", "Off-grid Inverter", "Wall-mounted Inverter", 
        "Solar Inverter", "Hybrid Inverter", "Pure Sine Wave Inverter", 
        "Energy Storage", "MPPT Controller", "Battery Backup", "Renewable Energy"
      ],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Hybrid 5KVA & 3KVA Wallmounted Inverter.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/General Wall Mounted Hybrid Inverter - 3KVA & 5KVA.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Hybrid 5KVA & 3KVA Wallmounted Inverter.jpg",
      name: "3KVA Offgrid Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "FL-MSD-400W",
      description: "High-efficiency 3KVA Off-grid wall-mounted inverter with pure sine wave output, compatible with solar and battery storage.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [
        "5KVA Inverter", "Off-grid Inverter", "Wall-mounted Inverter", 
        "Solar Inverter", "Hybrid Inverter", "Pure Sine Wave Inverter", 
        "Energy Storage", "MPPT Controller", "Battery Backup", "Renewable Energy"
      ],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Hybrid 5KVA & 3KVA Wallmounted Inverter.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/General Wall Mounted Hybrid Inverter - 3KVA & 5KVA.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Luminous Hybrid 1.5KVA & 850VA Inverter.webp",
      name: "Luminous 1.5KVA Offgrid Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "FL-MSD-400W",
      description: "High-efficiency Off-grid inverter with sine wave output, compatible with solar and battery storage.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [
        "1.5KVA Inverter", "Off-grid Inverter", "Wall-mounted Inverter", 
        "Solar Inverter", "Hybrid Inverter", "Pure Sine Wave Inverter", 
        "Energy Storage", "MPPT Controller", "Battery Backup", "Renewable Energy"
      ],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Hybrid 5KVA & 3KVA Wallmounted Inverter.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Luminous solar panel, inverter,battery datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Luminous Hybrid 1.5KVA & 850VA Inverter.webp",
      name: "Luminous 850VA Offgrid Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "FL-MSD-400W",
      description: "High-efficiency 3KVA Off-grid wall-mounted inverter with pure sine wave output, compatible with solar and battery storage.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [
        "5KVA Inverter", "Off-grid Inverter", "Wall-mounted Inverter", 
        "Solar Inverter", "Hybrid Inverter", "Pure Sine Wave Inverter", 
        "Energy Storage", "MPPT Controller", "Battery Backup", "Renewable Energy"
      ],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Hybrid 5KVA & 3KVA Wallmounted Inverter.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Luminous solar panel, inverter,battery datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPM 10KVA 48V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPM-10KVA-48V",
      description: "A high-efficiency inverter with a built-in MPPT charge controller, designed for optimized solar energy conversion, making it ideal for solar-powered systems.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["10KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPS 10KVA 48V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPS-10KVA-48V",
      description: "A reliable inverter with an integrated Battery Management System (BMS), focused on battery protection and longevity, best suited for home power backup solutions.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["10KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPM 7.5KVA 48V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPM-7.5KVA-48V",
      description: "A high-efficiency inverter with a built-in MPPT charge controller, designed for optimized solar energy conversion, making it ideal for solar-powered systems.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["7.5KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPS 7.5KVA 48V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPS-7.5KVA-48V",
      description: "A reliable inverter with an integrated Battery Management System (BMS), focused on battery protection and longevity, best suited for home power backup solutions.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["7.5KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPS 5KVA 48V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPS-5KVA-48V",
      description: "A reliable inverter with an integrated Battery Management System (BMS), focused on battery protection and longevity, best suited for home power backup solutions.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["5KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPM 5KVA 48V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPM-5KVA-48V",
      description: "A high-efficiency inverter with a built-in MPPT charge controller, designed for optimized solar energy conversion, making it ideal for solar-powered systems.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["5KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPM 5KVA 24V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPM-5KVA-24V",
      description: "A high-efficiency inverter with a built-in MPPT charge controller, designed for optimized solar energy conversion, making it ideal for solar-powered systems.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["5KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPM 3.5KVA 48V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPM-3.5KVA-48V",
      description: "A high-efficiency inverter with a built-in MPPT charge controller, designed for optimized solar energy conversion, making it ideal for solar-powered systems.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["3.5KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPM 3.5KVA 24V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPM-3.5KVA-24V",
      description: "A high-efficiency inverter with a built-in MPPT charge controller, designed for optimized solar energy conversion, making it ideal for solar-powered systems.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["3.5KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPS 3.5KVA 48V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPS-3.5KVA-48V",
      description: "A reliable inverter with an integrated Battery Management System (BMS), focused on battery protection and longevity, best suited for home power backup solutions.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["3.5KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPS 3.5KVA 24V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPS-3.5KVA-24V",
      description: "A reliable inverter with an integrated Battery Management System (BMS), focused on battery protection and longevity, best suited for home power backup solutions.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["3.5KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPM 2.5KVA 24V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPM-2.5KVA-24V",
      description: "A high-efficiency inverter with a built-in MPPT charge controller, designed for optimized solar energy conversion, making it ideal for solar-powered systems.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["2.5KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPM 2.5KVA 12V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPM-2.5KVA-12V",
      description: "A high-efficiency inverter with a built-in MPPT charge controller, designed for optimized solar energy conversion, making it ideal for solar-powered systems.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["2.5KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      name: "felicity IVPS 7.5KVA 48V Inverter",
      id: "234askfhjebjdyuw1",
      brandID: "IVPS-7.5KVA-48V",
      description: "A reliable inverter with an integrated Battery Management System (BMS), focused on battery protection and longevity, best suited for home power backup solutions.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["7.5KVA Inverter", "Off-grid Inverter", "Solar Inverter", 
        "Hybrid Inverter", "Pure Sine Wave", "MPPT Charger", 
        "Battery Inverter", "High Frequency Inverter", "Energy Storage"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Felicity Inverter Series.avif",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Felicity IVPS-IVPMSeriesManual2024-11-14.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Lumonous 220Ah Wet Cell Battery Inverlast.png",
      name: "Luminous 220Ah Tubular Battery",
      id: "234askfhjebjdyuw1",
      brandID: "FL-MSD-400W",
      description: "Reliable and long-lasting Inverlast 220Ah tubular battery, ideal for solar and inverter backup applications.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [
        "220Ah Battery", "Tubular Battery", "Deep Cycle Battery", 
        "Inverter Battery", "Solar Battery", "Battery Backup", 
        "Energy Storage", "Off-grid Power", "Luminous Battery", "Lead Acid Battery"
      ],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Lumonous 220Ah Wet Cell Battery Inverlast.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Luminous solar panel, inverter,battery datasheet.pdf",
    },

    {
      image: "./assets/e-Store Assets/Products/Lumonous 220Ah Tubular Battery NRGT.png",
      name: "Luminous 220Ah Tubular Battery",
      id: "234askfhjebjdyuw1",
      brandID: "FL-MSD-400W",
      description: "Reliable and long-lasting NRGT 220Ah tubular battery, ideal for solar and inverter backup applications.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [
        "220Ah Battery", "Tubular Battery", "Deep Cycle Battery", 
        "Inverter Battery", "Solar Battery", "Battery Backup", 
        "Energy Storage", "Off-grid Power", "Luminous Battery", "Lead Acid Battery"
      ],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Lumonous 220Ah Tubular Battery NRGT.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Luminous solar panel, inverter,battery datasheet.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/LPBA 48V 200Ah 10kWh Grade A Lithium Phosphate Solar Battery Pack with BMS by Felicity Solar.jpeg",
      name: "felicity 48V 200Ah 10kWh Li Battery",
      id: "234askfhjebjdyuw1",
      brandID: "LPBA48200",
      description: "Reliable and long-lasting Grade A lithium phosphate solar battery pack with BMS by Felicity Solar. Ideal for solar and inverter backup applications.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["48V Battery", "200Ah Battery", "Lithium Battery", 
        "Solar Battery", "Battery Backup", "Energy Storage", 
        "Deep Cycle Battery", "Off-grid Power", "Inverter Battery", 
        "Lithium Phosphate Battery"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/LPBA 48V 200Ah 10kWh Grade A Lithium Phosphate Solar Battery Pack with BMS by Felicity Solar.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/LPBA48200-IIManual2025-1-17.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/LPBF 24V 100ah M 2.5KWH Home Use Energy Storage Lithium Battery.jpeg",
      name: "felicity 24V 100Ah 10kWh Li Battery",
      id: "234askfhjebjdyuw1",
      brandID: "LPBF24100-M",
      description: "Reliable and long-lasting Grade A lithium phosphate solar battery pack with BMS by Felicity Solar. Ideal for solar and inverter backup applications.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["24V Battery", "100Ah Battery", "Lithium Battery", 
        "Solar Battery", "Battery Backup", "Energy Storage", 
        "Deep Cycle Battery", "Off-grid Power", "Inverter Battery", 
        "Lithium Phosphate Battery"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/LPBF 24V 100ah M 2.5KWH Home Use Energy Storage Lithium Battery.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/LPBF24100-MManual2024-9-24.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/LPBF 100Ah 48V 5KWH LiFePO4 Power Wall Mounted Lithium Battery For Solar System.jpeg",
      name: "felicity 48V 100Ah 10kWh Li Battery",
      id: "234askfhjebjdyuw1",
      brandID: "LPBF48100-H",
      description: "Reliable and long-lasting Grade A lithium phosphate solar battery pack with BMS by Felicity Solar. Ideal for solar and inverter backup applications.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["48V Battery", "100Ah Battery", "Lithium Battery", 
        "Solar Battery", "Battery Backup", "Energy Storage", 
        "Deep Cycle Battery", "Off-grid Power", "Inverter Battery", 
        "Lithium Phosphate Battery"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/LPBF 100Ah 48V 5KWH LiFePO4 Power Wall Mounted Lithium Battery For Solar System.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/LPBF48100-MManual2024-12-27.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/LPBF 17.5kWh 48V 350Ah Rechargeable LiFePO4 Battery Solar Pack with BMS by Felicity Solar.jpeg",
      name: "felicity 48V 350Ah 17.5kWh Li Battery",
      id: "234askfhjebjdyuw1",
      brandID: "LPBF48350",
      description: "Reliable and long-lasting Grade A lithium phosphate solar battery pack with BMS by Felicity Solar. Ideal for solar and inverter backup applications.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["48V Battery", "350Ah Battery", "Lithium Battery", 
        "Solar Battery", "Battery Backup", "Energy Storage", 
        "Deep Cycle Battery", "Off-grid Power", "Inverter Battery", 
        "Lithium Phosphate Battery"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/LPBF 17.5kWh 48V 350Ah Rechargeable LiFePO4 Battery Solar Pack with BMS by Felicity Solar.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/LPBF48350Manual2024-9-13.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/LPBF 200ah 48V H 10KWH Lifepo4 Power Wall Lithium Battery For Off Grid Solar System.jpeg",
      name: "felicity 48V 200Ah 10kWh LiFePO₄ Battery",
      id: "234askfhjebjdyuw1",
      brandID: "LPBF48200-H",
      description: "Reliable and long-lasting Grade A lithium phosphate (LiFePO₄) solar battery pack with BMS by Felicity Solar. Ideal for solar and inverter backup applications.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["48V Battery", "200Ah Battery", "Lithium Battery", 
        "Solar Battery", "Battery Backup", "Energy Storage", 
        "Deep Cycle Battery", "Off-grid Power", "Inverter Battery", 
        "Lithium Phosphate Battery"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/LPBF 200ah 48V H 10KWH Lifepo4 Power Wall Lithium Battery For Off Grid Solar System.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/LPBF48100-H-LPBF48200-HManual2024-12-27.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/LPBF48150-P.jpeg",
      name: "felicity 48V 150Ah 7.5kWh LiFePO₄ Battery",
      id: "234askfhjebjdyuw1",
      brandID: "LPBF48150-P",
      description: "Reliable and long-lasting Grade A lithium phosphate (LiFePO₄) solar battery pack with BMS by Felicity Solar. Ideal for solar and inverter backup applications.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["48V Battery", "150Ah Battery", "Lithium Battery", 
        "Solar Battery", "Battery Backup", "Energy Storage", 
        "Deep Cycle Battery", "Off-grid Power", "Inverter Battery", 
        "Lithium Phosphate Battery"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/LPBF48150-P.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/LPBF48150-P.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/FLA48250.jpeg",
      name: "felicity 24V 200Ah 4.8kWh LiFePO₄ Battery",
      id: "234askfhjebjdyuw1",
      brandID: "FLA48250",
      description: "Reliable and long-lasting Grade A lithium phosphate (LiFePO₄) solar battery pack with BMS by Felicity Solar. Ideal for solar and inverter backup applications.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["48V Battery", "200Ah Battery", "Lithium Battery", 
        "Solar Battery", "Battery Backup", "Energy Storage", 
        "Deep Cycle Battery", "Off-grid Power", "Inverter Battery", 
        "Lithium Phosphate Battery"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/FLA48250.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/FLA48250.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/FLA48300.jpeg",
      name: "felicity 48V 300Ah 15kWh LiFePO₄ Battery",
      id: "234askfhjebjdyuw1",
      brandID: "FLA48200",
      description: "Reliable and long-lasting Grade A lithium phosphate (LiFePO₄) solar battery pack with BMS by Felicity Solar. Ideal for solar and inverter backup applications.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["48V Battery", "300Ah Battery", "Lithium Battery", 
        "Solar Battery", "Battery Backup", "Energy Storage", 
        "Deep Cycle Battery", "Off-grid Power", "Inverter Battery", 
        "Lithium Phosphate Battery"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/FLA48300.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/FLA48300.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/FLA48500.jpeg",
      name: "felicity 48V 500Ah 25kWh LiFePO₄ Battery",
      id: "234askfhjebjdyuw1",
      brandID: "FLA48500",
      description: "Reliable and long-lasting Grade A lithium phosphate (LiFePO₄) solar battery pack with BMS by Felicity Solar. Ideal for solar and inverter backup applications.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["48V Battery", "500Ah Battery", "Lithium Battery", 
        "Solar Battery", "Battery Backup", "Energy Storage", 
        "Deep Cycle Battery", "Off-grid Power", "Inverter Battery", 
        "Lithium Phosphate Battery"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/FLA48500.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/FLA48500.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/LPBA48200-II.jpeg",
      name: "felicity 48V 200Ah 10kWh LiFePO₄ Battery",
      id: "234askfhjebjdyuw1",
      brandID: "LPBA48200-II",
      description: "Reliable and long-lasting Grade A lithium phosphate (LiFePO₄) solar battery pack with BMS by Felicity Solar. Ideal for solar and inverter backup applications.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["48V Battery", "200Ah Battery", "Lithium Battery", 
        "Solar Battery", "Battery Backup", "Energy Storage", 
        "Deep Cycle Battery", "Off-grid Power", "Inverter Battery", 
        "Lithium Phosphate Battery"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/LPBA48200-II.jpeg",
      },
      // pdf: "./assets/e-Store Assets/Datasheets/FLA48500.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/FL-A3-30W.png",
      name: "felicity A3 30W All-In-One Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "FL-A3-30W",
      description: "High-efficiency all-in-one solar street lamp with integrated lithium battery and LED lighting system by Felicity Solar. Ideal for outdoor lighting, street illumination, and security lighting.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/FL-A3-30W.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/FelicitySL-20241121.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/FL-A3-30W.png",
      name: "felicity A3 40W All-In-One Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "FL-A3-40W",
      description: "High-efficiency all-in-one solar street lamp with integrated lithium battery and LED lighting system by Felicity Solar. Ideal for outdoor lighting, street illumination, and security lighting.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/FL-A3-30W.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/FelicitySL-20241121.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/A3-60W-P.png",
      name: "felicity A3 60W All-In-One Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "A3-60W-P",
      description: "High-efficiency all-in-one solar street lamp with integrated lithium battery and LED lighting system by Felicity Solar. Ideal for outdoor lighting, street illumination, and security lighting.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/A3-60W-P.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/FelicitySL-20241121.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/A3-100W-S.png",
      name: "felicity A3 100W-S All-In-One Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "A3-100W-S",
      description: "High-efficiency all-in-one solar street lamp with integrated lithium battery and LED lighting system by Felicity Solar. Ideal for outdoor lighting, street illumination, and security lighting.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/A3-100W-S.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/FelicitySL-20241121.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/A3-150W.png",
      name: "felicity A3 150W-S All-In-One Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "A3-150W",
      description: "High-efficiency all-in-one solar street lamp with integrated lithium battery and LED lighting system by Felicity Solar. Ideal for outdoor lighting, street illumination, and security lighting.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/A3-150W.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/FelicitySL-20241121.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/D2-30W-P.png",
      name: "felicity D2 30W-P All-In-One Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "D2-30W-P",
      description: "High-efficiency all-in-one solar street lamp with integrated lithium battery and LED lighting system by Felicity Solar. Ideal for outdoor lighting, street illumination, and security lighting.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/D2-30W-P.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/D2-30W-P.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/D2-40W-P.jpeg",
      name: "felicity D2 40W-P All-In-One Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "D2-40W-P",
      description: "High-efficiency all-in-one solar street lamp with integrated lithium battery and LED lighting system by Felicity Solar. Ideal for outdoor lighting, street illumination, and security lighting.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/D2-40W-P.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/D2-30W-P.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/D2-60W-P.jpeg",
      name: "felicity D2 60W-P All-In-One Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "D2-60W-P",
      description: "High-efficiency all-in-one solar street lamp with integrated lithium battery and LED lighting system by Felicity Solar. Ideal for outdoor lighting, street illumination, and security lighting.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/D2-60W-P.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/D2-30W-P.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/D2-30W-P.png",
      name: "felicity D2 80W-P All-In-One Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "D2-80W-P",
      description: "High-efficiency all-in-one solar street lamp with integrated lithium battery and LED lighting system by Felicity Solar. Ideal for outdoor lighting, street illumination, and security lighting.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/D2-80W-P.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/D2-30W-P.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/D2-30W-P.png",
      name: "felicity D2 100W-S All-In-One Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "D2-100W-S",
      description: "High-efficiency all-in-one solar street lamp with integrated lithium battery and LED lighting system by Felicity Solar. Ideal for outdoor lighting, street illumination, and security lighting.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/D2-30W-P.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/D2-30W-P.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/D2-30W-P.png",
      name: "felicity D2 120W-S All-In-One Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "D2-120W-S",
      description: "High-efficiency all-in-one solar street lamp with integrated lithium battery and LED lighting system by Felicity Solar. Ideal for outdoor lighting, street illumination, and security lighting.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/D2-30W-P.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/D2-30W-P.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/D2-30W-P.png",
      name: "felicity D2 150W-S All-In-One Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "D2-150W-S",
      description: "High-efficiency all-in-one solar street lamp with integrated lithium battery and LED lighting system by Felicity Solar. Ideal for outdoor lighting, street illumination, and security lighting.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/D2-30W-P.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/D2-30W-P.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/F1-60W.png",
      name: "felicity F1 60W IP65 Sensor Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "F1-60W",
      description: "High-efficiency 60W all-in-one solar street lamp with an integrated lithium battery and LED lighting system by Felicity Solar. Designed for outdoor lighting, security applications, and street illumination. Features motion sensor, automatic dusk-to-dawn operation, and IP65-rated weatherproof housing.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "IP65", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/F1-60W.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/F1-60W-120W.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/F1-60W.png",
      name: "felicity F1 80W IP65 Sensor Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "F1-80W",
      description: "High-efficiency 80W all-in-one solar street lamp with an integrated lithium battery and LED lighting system by Felicity Solar. Designed for outdoor lighting, security applications, and street illumination. Features motion sensor, automatic dusk-to-dawn operation, and IP65-rated weatherproof housing.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "IP65", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/F1-60W.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/F1-60W-120W.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/F1-100W.JPEG",
      name: "felicity F1 100W IP65 Sensor Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "F1-100W",
      description: "High-efficiency 100W all-in-one solar street lamp with an integrated lithium battery and LED lighting system by Felicity Solar. Designed for outdoor lighting, security applications, and street illumination. Features motion sensor, automatic dusk-to-dawn operation, and IP65-rated weatherproof housing.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "IP65", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/F1-100W.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/F1-60W-120W.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/F1-120W.png",
      name: "felicity F1 120W IP65 Sensor Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "F1-120W",
      description: "High-efficiency 120W all-in-one solar street lamp with an integrated lithium battery and LED lighting system by Felicity Solar. Designed for outdoor lighting, security applications, and street illumination. Features motion sensor, automatic dusk-to-dawn operation, and IP65-rated weatherproof housing.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "IP65", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/F1-120W.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/F1-60W-120W.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/P2-40W.JPEG",
      name: "felicity P2 40W Sensor Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "P2-40W",
      description: "High-efficiency 40W all-in-one solar street lamp with an integrated lithium battery and LED lighting system by Felicity Solar. Designed for outdoor lighting, security applications, and street illumination. Features motion sensor, automatic dusk-to-dawn operation, and IP65-rated weatherproof housing.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "IP65", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/P2-40W.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/P2-40W-80W.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/P2-60W.jpg",
      name: "felicity P2 60W Sensor Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "P2-60W",
      description: "High-efficiency 60W all-in-one solar street lamp with an integrated lithium battery and LED lighting system by Felicity Solar. Designed for outdoor lighting, security applications, and street illumination. Features motion sensor, automatic dusk-to-dawn operation, and IP65-rated weatherproof housing.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "IP65", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/P2-60W.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/P2-40W-80W.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/P2-80W.JPG",
      name: "felicity P2 80W Sensor Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "P2-80W",
      description: "High-efficiency 80W all-in-one solar street lamp with an integrated lithium battery and LED lighting system by Felicity Solar. Designed for outdoor lighting, security applications, and street illumination. Features motion sensor, automatic dusk-to-dawn operation, and IP65-rated weatherproof housing.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "IP65", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/P2-80W.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/P2-40W-80W.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/P3-60W.JPG",
      name: "felicity P3 60W Sensor Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "P3-60W",
      description: "High-efficiency 60W all-in-one solar street lamp with an integrated lithium battery and LED lighting system by Felicity Solar. Designed for outdoor lighting, security applications, and street illumination. Features motion sensor, automatic dusk-to-dawn operation, and IP65-rated weatherproof housing.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "IP65", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/P3-60W.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/P3-60W&80W.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/P3-60W.JPG",
      name: "felicity P3 80W Sensor Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "P3-80W",
      description: "High-efficiency 80W all-in-one solar street lamp with an integrated lithium battery and LED lighting system by Felicity Solar. Designed for outdoor lighting, security applications, and street illumination. Features motion sensor, automatic dusk-to-dawn operation, and IP65-rated weatherproof housing.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "IP65", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/P3-60W.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/P3-60W&80W.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/P3-60W.JPG",
      name: "felicity P3 60W Sensor Lamp",
      id: "234askfhjebjdyuw1",
      brandID: "P3-60W",
      description: "High-efficiency 60W all-in-one solar street lamp with an integrated lithium battery and LED lighting system by Felicity Solar. Designed for outdoor lighting, security applications, and street illumination. Features motion sensor, automatic dusk-to-dawn operation, and IP65-rated weatherproof housing.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Lamp", "IP65", "All-in-One Lamp", "Street Light", 
    "Outdoor Lighting", "LED Lamp", "Solar Lighting", 
    "Energy Efficient Lamp"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/P3-60W.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/P3-60W&80W.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/Smart WiFi-S.JPEG",
      name: "Wifi Module/Dongle",
      id: "234askfhjebjdyuw1",
      brandID: "Smart WiFi-S",
      description: "Compact and high-performance WiFi module/dongle designed for seamless wireless connectivity. Ideal for smart home automation, remote monitoring, and IoT applications. Supports secure and fast data transmission with low power consumption.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [    "WiFi Module", "Smart Dongle", "Wireless Adapter",
        "IoT Connectivity", "Smart Home", "Remote Monitoring",
        "WiFi Extender", "Internet Dongle", "Plug and Play"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/Smart WiFi-S.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/Smart WiFi-S.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/A11-ST Cable.JPEG",
      name: "European Standard 11KW AC Charging Pile Home Charger Car Charge Atlas AC Charger",
      id: "234askfhjebjdyuw1",
      brandID: "A11-ST Cable",
      description: "Reliable and efficient 11kW AC home charging pile for electric vehicles. Designed for fast and safe charging with European standard compliance. Features an intelligent control system, Type 2 plug compatibility, and robust weatherproof construction.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [        "EV Charger", "Home Charging Station", "11kW Charger",
        "Electric Vehicle Charger", "Type 2 EV Charger",
        "Wall-mounted Charger", "Smart EV Charging",
        "Sustainable Mobility", "Fast Charging"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/A11-ST Cable.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/A11&A7-ST Cable.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/A11-ST Cable.JPEG",
      name: "European Standard 7KW AC Charging Pile Home Charger Car Charge Atlas AC Charger",
      id: "234askfhjebjdyuw1",
      brandID: "A7-ST Cable",
      description: "Reliable and efficient 7kW AC home charging pile for electric vehicles. Designed for fast and safe charging with European standard compliance. Features an intelligent control system, Type 2 plug compatibility, and robust weatherproof construction.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [        "EV Charger", "Home Charging Station", "11kW Charger",
        "Electric Vehicle Charger", "Type 2 EV Charger",
        "Wall-mounted Charger", "Smart EV Charging",
        "Sustainable Mobility", "Fast Charging"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/A11-ST Cable.jpeg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/A11&A7-ST Cable.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-1800-HR-04H-600x600-1.JPG",
      name: "Lorentz PS2-1800-HR-07 Helical Rotor Solar Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-1800-HR-07",
      description: "High-efficiency helical rotor solar submersible pump designed for reliable water supply in off-grid locations. Ideal for agriculture, irrigation, livestock watering, and rural water supply. Powered by solar energy, it ensures sustainable and cost-effective water pumping with maximum efficiency.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "Submersible Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Deep Well Pump", "Water Pump for Farms",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-1800-HR-04H-600x600-1.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-1800-HR-04H-600x600-1.JPG",
      name: "Lorentz PS2-1800-HR-05HL Helical Rotor Solar Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-1800-HR-05HL",
      description: "High-efficiency helical rotor solar submersible pump designed for reliable water supply in off-grid locations. Ideal for agriculture, irrigation, livestock watering, and rural water supply. Powered by solar energy, it ensures sustainable and cost-effective water pumping with maximum efficiency.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "Submersible Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Deep Well Pump", "Water Pump for Farms",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-1800-HR-04H-600x600-1.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-1800-HR-04H-600x600-1.JPG",
      name: "Lorentz PS2-1800-HR-04H Helical Rotor Solar Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-1800-HR-04H",
      description: "High-efficiency helical rotor solar submersible pump designed for reliable water supply in off-grid locations. Ideal for agriculture, irrigation, livestock watering, and rural water supply. Powered by solar energy, it ensures sustainable and cost-effective water pumping with maximum efficiency.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "Submersible Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Deep Well Pump", "Water Pump for Farms",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-1800-HR-04H-600x600-1.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-1800-HR-04H-600x600-1.JPG",
      name: "Lorentz PS2-1800-HR-04 Helical Rotor Solar Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-1800-HR-04",
      description: "High-efficiency helical rotor solar submersible pump designed for reliable water supply in off-grid locations. Ideal for agriculture, irrigation, livestock watering, and rural water supply. Powered by solar energy, it ensures sustainable and cost-effective water pumping with maximum efficiency.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "Submersible Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Deep Well Pump", "Water Pump for Farms",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-1800-HR-04H-600x600-1.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-1800-HR-04H-600x600-1.JPG",
      name: "Lorentz PS2-1800-HR-03H Helical Rotor Solar Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-1800-HR-03H",
      description: "High-efficiency helical rotor solar submersible pump designed for reliable water supply in off-grid locations. Ideal for agriculture, irrigation, livestock watering, and rural water supply. Powered by solar energy, it ensures sustainable and cost-effective water pumping with maximum efficiency.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "Submersible Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Deep Well Pump", "Water Pump for Farms",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-1800-HR-04H-600x600-1.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-1800-HR-04H-600x600-1.JPG",
      name: "Lorentz PS2-1800-HR-03 Helical Rotor Solar Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-1800-HR-03",
      description: "High-efficiency helical rotor solar submersible pump designed for reliable water supply in off-grid locations. Ideal for agriculture, irrigation, livestock watering, and rural water supply. Powered by solar energy, it ensures sustainable and cost-effective water pumping with maximum efficiency.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "Submersible Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Deep Well Pump", "Water Pump for Farms",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-1800-HR-04H-600x600-1.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-1800-CS-F12-2.JPG",
      name: "Lorentz PS2-1800-CS-F12-2 Solar Surface Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-1800-CS-F12-2",
      description: "High-performance solar surface pump designed for efficient water transfer and distribution. Ideal for irrigation, livestock watering, and rural water supply. Operates on solar power, ensuring cost-effective and eco-friendly water pumping with minimal maintenance.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [    "Solar Water Pump", "Surface Pump", "Water Transfer Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Water Pump for Farms",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-1800-CS-F12-2.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-1800-CS-F12-2.JPG",
      name: "Lorentz PS2-1800-CS-F4-6 Solar Surface Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-1800-CS-F4-6",
      description: "Efficient solar-powered surface pump designed for reliable water supply in off-grid applications. Ideal for agricultural irrigation, livestock watering, and community water distribution. Features high-performance efficiency, low maintenance, and sustainable solar operation.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [    "Solar Water Pump", "Surface Pump", "Water Transfer Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Water Pump for Farms",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-1800-CS-F12-2.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-1800-CS-37-1.JPG",
      name: "Lorentz PS2-1800-CS-F4-6 Solar Surface Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-1800-CS-37-1",
      description: "Efficient solar-powered surface pump designed for reliable water supply in off-grid applications. Ideal for agricultural irrigation, livestock watering, and community water distribution. Features high-performance efficiency, low maintenance, and sustainable solar operation.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [    "Solar Water Pump", "Surface Pump", "Water Transfer Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Water Pump for Farms",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-1800-CS-37-1.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-1800-C-SJ1-25.JPG",
      name: "Lorentz PS2-1800-C-SJ1-25 Solar Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-1800-C-SJ1-25",
      description: "Efficient solar-powered surface pump designed for reliable water supply in off-grid applications. Ideal for agricultural irrigation, livestock watering, and community water distribution. Features high-performance efficiency, low maintenance, and sustainable solar operation.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [    "Solar Water Pump", "Surface Pump", "Water Transfer Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Water Pump for Farms",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-1800-C-SJ1-25.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-1800-C-SJ1-25.JPG",
      name: "Lorentz PS2-600-SJ8-5 Centrifugal Submersible Solar Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-600-SJ8-5",
      description: "High-performance solar-powered centrifugal submersible pump for efficient water supply. Designed for agricultural irrigation, livestock watering, and rural water distribution. Operates on solar energy, ensuring reliable and sustainable pumping with minimal maintenance.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Centrifugal Pump", "Submersible Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Deep Well Pump", "Water Pump for Farms",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-1800-C-SJ1-25.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-600.png",
      name: "Lorentz PS2-600-Helical Rotor-14 Solar Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-600-14",
      description: "Efficient solar-powered helical rotor pump for high-lift water pumping applications. Designed for off-grid water supply, agricultural irrigation, livestock watering, and deep well extraction. Operates on solar energy, providing reliable, low-maintenance, and sustainable water pumping.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "High-Lift Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Deep Well Pump",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-600.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-600.png",
      name: "Lorentz PS2-600-Helical Rotor-10 Solar Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-600-10",
      description: "Efficient solar-powered helical rotor pump for high-lift water pumping applications. Designed for off-grid water supply, agricultural irrigation, livestock watering, and deep well extraction. Operates on solar energy, providing reliable, low-maintenance, and sustainable water pumping.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "High-Lift Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Deep Well Pump",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-600.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-600.png",
      name: "Lorentz PS2-600-Helical Rotor-7 Solar Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-600-7",
      description: "Efficient solar-powered helical rotor pump for high-lift water pumping applications. Designed for off-grid water supply, agricultural irrigation, livestock watering, and deep well extraction. Operates on solar energy, providing reliable, low-maintenance, and sustainable water pumping.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "High-Lift Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Deep Well Pump",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-600.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-600.jpg",
      name: "Lorentz PS2-600-Helical Rotor-04H Solar Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-600-04H",
      description: "Efficient solar-powered helical rotor pump for high-lift water pumping applications. Designed for off-grid water supply, agricultural irrigation, livestock watering, and deep well extraction. Operates on solar energy, providing reliable, low-maintenance, and sustainable water pumping.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "High-Lift Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Deep Well Pump",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-600.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-600.jpg",
      name: "Lorentz PS2-600-Helical Rotor-04 Solar Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-600-04",
      description: "Efficient solar-powered helical rotor pump for high-lift water pumping applications. Designed for off-grid water supply, agricultural irrigation, livestock watering, and deep well extraction. Operates on solar energy, providing reliable, low-maintenance, and sustainable water pumping.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "High-Lift Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Deep Well Pump",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-600.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-600.jpg",
      name: "Lorentz PS2-600-Helical-Rotor-03H Solar Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-600-03H",
      description: "Efficient solar-powered helical rotor pump for high-lift water pumping applications. Designed for off-grid water supply, agricultural irrigation, livestock watering, and deep well extraction. Operates on solar energy, providing reliable, low-maintenance, and sustainable water pumping.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "High-Lift Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Deep Well Pump",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-600.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-600.jpg",
      name: "Lorentz PS2-600-Helical-Rotor-03 Solar Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-600-03",
      description: "Efficient solar-powered helical rotor pump for high-lift water pumping applications. Designed for off-grid water supply, agricultural irrigation, livestock watering, and deep well extraction. Operates on solar energy, providing reliable, low-maintenance, and sustainable water pumping.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "High-Lift Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Deep Well Pump",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-600.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-600-C-SJ5-8.jpg",
      name: "Lorentz PS2-600-C-SJ5-8 Solar Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-600-C-SJ5-8",
      description: "High-performance solar-powered centrifugal submersible pump designed for efficient water transfer and supply. Ideal for agricultural irrigation, livestock watering, and rural water distribution. Operates on solar energy, ensuring reliable and sustainable water pumping with minimal maintenance.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Centrifugal Pump", "Submersible Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Deep Well Pump", "Water Pump for Farms",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-600-C-SJ5-8.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS1800-Pool-CS-37-1.png",
      name: "Lorentz PS1800-Pool-CS-37-1 Controller",
      id: "234askfhjebjdyuw1",
      brandID: "PS1800-Pool-CS-37-1",
      description: "High-performance solar-powered centrifugal submersible pump designed for efficient water transfer and supply. Ideal for agricultural irrigation, livestock watering, rural water distribution, and pool applications. Operates on solar energy, ensuring reliable and sustainable water pumping with minimal maintenance.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: [    "Solar Water Pump", "Centrifugal Pump", "Submersible Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Deep Well Pump", "Water Pump for Farms",
        "Renewable Energy Pump", "Pool Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS1800-Pool-CS-37-1.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2150.png",
      name: "Lorentz PS2-150 Controller",
      id: "234askfhjebjdyuw1",
      brandID: "PS2150",
      description: "High-performance controller for solar-powered centrifugal submersible pumps. Designed to manage efficient water transfer and supply for applications such as agricultural irrigation, livestock watering, rural water distribution, and pool systems. Operates with solar energy, ensuring reliable and sustainable operation with minimal maintenance.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Pump Controller", "Centrifugal Pump Controller", "Water Pump Controller",
        "Irrigation Controller", "Off-grid Water Supply", "Solar-Powered Controller",
        "Agricultural Pump Controller", "Deep Well Controller", "Water Distribution Controller",
        "Pool Pump Controller"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2150.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-600.png",
      name: "Lorentz PS2-200 Helical Rotor 14 Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-200-14",
      description: "Efficient solar-powered helical rotor pump for high-lift water pumping applications. Designed for off-grid water supply, agricultural irrigation, livestock watering, and deep well extraction. Operates on solar energy, providing reliable, low-maintenance, and sustainable water pumping.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "High-Lift Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Deep Well Pump",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-600.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-600.png",
      name: "Lorentz PS2-200 Helical Rotor 7 Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-200-7",
      description: "Efficient solar-powered helical rotor pump for high-lift water pumping applications. Designed for off-grid water supply, agricultural irrigation, livestock watering, and deep well extraction. Operates on solar energy, providing reliable, low-maintenance, and sustainable water pumping.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Helical Rotor Pump", "High-Lift Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Deep Well Pump",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-600.png",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-150-C-SJ5-8.jpg",
      name: "Lorentz PS2-150 C SJ5 8 Submersible Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-200-7",
      description: "Efficient solar-powered submersible pump designed for high-lift water pumping applications. The Lorentz PS2-150 C SJ5 8 is ideal for off-grid water supply, agricultural irrigation, livestock watering, and deep well extraction. Powered by solar energy, it ensures a reliable, low-maintenance, and sustainable water pumping solution.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Submersible Pump", "High-Lift Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Deep Well Pump",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-150-C-SJ5-8.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-150-BOOST-240.jpg",
      name: "Lorentz PS2-150-BOOST-240 Surface Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-150-BOOST-240",
      description: "Efficient solar-powered submersible pump designed for high-lift water pumping applications. The Lorentz PS2-150 C SJ5 8 is ideal for off-grid water supply, agricultural irrigation, livestock watering, and deep well extraction. Powered by solar energy, it ensures a reliable, low-maintenance, and sustainable water pumping solution.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Submersible Pump", "High-Lift Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Deep Well Pump",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-150-BOOST-240.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
    {
      image: "./assets/e-Store Assets/Products/PS2-150-BOOST-240.jpg",
      name: "Lorentz PS2-150-BOOST-125 Surface Pump",
      id: "234askfhjebjdyuw1",
      brandID: "PS2-150-BOOST-240",
      description: "Efficient solar-powered submersible pump designed for high-lift water pumping applications. The Lorentz PS2-150 C SJ5 8 is ideal for off-grid water supply, agricultural irrigation, livestock watering, and deep well extraction. Powered by solar energy, it ensures a reliable, low-maintenance, and sustainable water pumping solution.",
      rating: { stars: 4.5, count: 87 },
      price: 169000,
      keywords: ["Solar Water Pump", "Submersible Pump", "High-Lift Pump",
        "Irrigation Pump", "Off-grid Water Supply", "Solar-Powered Pump",
        "Agricultural Pump", "Livestock Watering", "Deep Well Pump",
        "Renewable Energy Pump"],
      relatedImages: {
        img1: "./assets/e-Store Assets/Products/PS2-150-BOOST-240.jpg",
      },
      pdf: "./assets/e-Store Assets/Datasheets/PS2-150 to PS2-4000.pdf",
    },
3        



  ];
  
  // the cart variable - containing items added to the cart
  const cart = [];
  

  const productsContainer = document.getElementById("products-container");
  const cartCount = document.getElementById("cart-count");
  const modal = document.getElementById("details-modal");
  const modalDetails = document.getElementById("modal-details");
  const closeModal = document.getElementById("close-modal");
  
  function renderProducts() {
    products.forEach((product) => {
      const productDiv = document.createElement("div");
      productDiv.className = "product";
      productDiv.innerHTML = `
        <img src="${product.image}" alt="${product.name}">
        <h3>${product.name}</h3>

        <div class="price">₦${product.price.toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
        <div class="rating">⭐ ${product.rating.stars} (${product.rating.count} reviews)</div>
        <button class="add">Add to Cart</button>
        <button class="details">View Details</button>
      `;
  
      productDiv.querySelector(".add").addEventListener("click", () => {
        cart.push(product);
        cartCount.textContent = cart.length;
      });
  
      productDiv.querySelector(".details").addEventListener("click", () => {
        showDetails(product);
      });
  
      productsContainer.appendChild(productDiv);
    });
  }
  
  renderProducts();
  
  function showDetails(product) {
    modalDetails.innerHTML = `


            <div class="display-box">
                <img id="main-display-image" src="${product.relatedImages.img1}" alt="Product Image" />
            </div>


 
        <div class="product-table-detail">
            <table>
                <tr><th>Name</th><td>${product.name}</td></tr>
                <tr><th>Description</th><td>${product.description}</td></tr>
                <tr><th>Price</th><td>₦${product.price.toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td></tr>
                <tr><th>Rating</th><td>${product.rating.stars} stars (${product.rating.count} reviews)</td></tr>
            </table>
        </div>
        <iframe class="pdf-preview" src="${product.pdf}" width="100%" height="500px"></iframe>
        
        <div class="order-now-btn">
          <button class="order-btn">Order Now</button>
        </div>

                <!-- WhatsApp Button -->
        <div class="whatsapp-now-btn">
            <a href="https://wa.me/2349053083075?text=I%20am%20interested%20in%20ordering%20${encodeURIComponent(product.name)}%20for%20₦${product.price}" target="_blank">
                <button class="whatsapp-btn">WhatsApp</button>
            </a>
        </div>

    </div>
    `;

    modal.style.display = "flex";
}

// Close modal event
closeModal.addEventListener("click", () => {
  modal.style.display = "none";
});
